export const DEFAULT_SETTINGS = Object.freeze({
  POSTGRES_PORT: '5432',
  POSTGRES_DB: 'dev',
  POSTGRES_USER: 'dev',
  POSTGRES_PASSWORD: 'dev',
  IPFS_PORT: '5001',
  ETHEREUM_PORT: '8545',
  ETHEREUM_NETWORK: 'hardhat',
  GRAPH_NODE_GRAPHQL_PORT: '8000',
  GRAPH_NODE_STATUS_PORT: '8020',
});